---
- name: Install Prerequisites for Zabbix-3.4.1
  yum: 
    name: "{{ item }}"
    state: present
  with_items:
    - libevent
    - libevent-devel
    - rsync
    - net-snmp
    - net-snmp-devel  
    - libcurl-devel
    - OpenIPMI
    - OpenIPMI-tools
    - OpenIPMI-libs
    - libssh2-devel
    - OpenIPMI-devel
    - MySQL-python
    - fping

- name: Download "{{ Zabbix_Version }}" Package, and release
  unarchive: src="{{ Down_Zabbix_Package }}" dest="{{ Release_dir }}" remote_src=True

- name: Download "{{ Iksemel_Version }}" Package, and release
  unarchive: src="{{ Down_Iksemel_Package }}" dest="{{ Release_dir }}" remote_src=True

- name: Download "{{ Iksemel_Script }}"
  get_url: url="{{ Down_Iksemel_Script }}" dest="{{ Release_dir }}/{{ Iksemel_Version }}"

- name: Run "{{ Iksemel_Script }}" 
  script: /bin/bash "{{ Release_dir}}/{{ Iksemel_Version }}/{{ Iksemel_Script }}" "{{ Iksemel_Version }}"

- name: Add an account for the Zabbix_Service
  user: name="{{ Zabbix_User }}" shell=/sbin/nologin createhome=no append=yes
  
- name: fping supported in the zabbix system
  command: chmod u+s /usr/sbin/fping

- name: Download "{{ Zabbix_Server_Script }}"
  get_url: url="{{ Down_Zabbix_Script }}" dest="{{ Release_dir }}/{{ Zabbix_Version }}"
  
- name: Run "{{ Zabbix_Server_Script }}" 
  script: /bin/bash "{{ Release_dir}}/{{ Zabbix_Version }}/{{ Zabbix_Server_Script }}" "{{ Zabbix_Version }}"

- name: ln zabbix file for service zabbix_start 01
  command: ln -s /usr/local/lib/libiksemel.so.3 /usr/lib64/

- name: ln zabbix file for service zabbix_start 02
  command: ln -s /safe/mysql/lib/libmysqlclient.so.18 /usr/lib64/

- name: Create a new database with name 'Zabbix',And Import schema
  mysql_db:
    login_user: "{{ MySQL_DB_User }}"
    login_password: "{{ MySQL_DB_Pwd }}"
    login_host: "{{ MySQL_DB_Host }}"
    state: import
    name: "{{ Zabbix_DB_DBName }}"
    target: "{{ Release_dir}}/{{ Zabbix_Version }}/database/mysql/schema.sql"
  ignore_errors: yes

- name: database with name 'Zabbix',And Import images
  mysql_db:
    login_user: "{{ MySQL_DB_User }}"
    login_password: "{{ MySQL_DB_Pwd }}"
    login_host: "{{ MySQL_DB_Host }}"
    state: import
    name: "{{ Zabbix_DB_DBName }}"
    target: "{{ Release_dir}}/{{ Zabbix_Version }}/database/mysql/images.sql"
  ignore_errors: yes

- name: database with name 'Zabbix',And Import data
  mysql_db:
    login_user: "{{ MySQL_DB_User }}"
    login_password: "{{ MySQL_DB_Pwd }}"
    login_host: "{{ MySQL_DB_Host }}"
    state: import
    name: "{{ Zabbix_DB_DBName }}"
    target: "{{ Release_dir}}/{{ Zabbix_Version }}/database/mysql/data.sql"
  ignore_errors: yes

- name: Create database user for Zabbix Project
  mysql_user:
    login_user: "{{ MySQL_DB_User }}"
    login_password: "{{ MySQL_DB_Pwd }}"
    host: "{{ Zabbix_DB_Host }}"
    name: "{{ Zabbix_DB_DBName }}"
    password: "{{ Zabbix_DB_Pwd }}"
    priv: "{{ Zabbix_DB_DBName }}.*:ALL"
    state: present
    update_password: always
    config_file: /etc/my.cnf
    login_unix_socket: /tmp/mysql.sock

- name: Import HTML into NGINX/monitor
  synchronize: 
    src: "{{ Release_dir}}/{{ Zabbix_Version }}/frontends/php/"
    dest: "{{Nginx_RootDir}}/monitor"

- name: Import HTML Configure monitor/conf
  template:
    src: zabbix.conf.php
    dest: "{{Nginx_RootDir}}/monitor/conf/zabbix.conf.php"
    mode: 0644
  become: yes

- name: Import Zabbix Server Configure file on Zabbix_Home
  template:
    src: zabbix_server.conf
    dest: "/usr/local/etc/zabbix_server.conf"
    mode: 0644
  become: yes
  
- name: Build zabbix_server file
  template:
    src: zabbix_server
    dest: /etc/init.d/zabbix_server
    mode: 0755
  become: yes

- name: Build zabbix_agent file
  template:
    src: zabbix_agentd
    dest: /etc/init.d/zabbix_agentd
    mode: 0755
  become: yes

- name: Delete Old ZABBIX_SERVICE File
  command: chkconfig --del zabbix_server
  
- name: Add New ZABBIX_SERVICE File
  command: chkconfig --add zabbix_server
  
- name: Configuration ZABBIX_SERVICE
  command: chkconfig zabbix_server on

  notify: restart nginx php-fpm zabbix_server
  