---
- name: restart nginx
  service: name=nginx state=restarted

- name: restart php-fpm
  service: name=php-fpm state=restarted

- name: restart zabbix_server
  service: name=zabbix_server state=restarted