---
- name: Install Prerequisites for PHP-5.6.30
  yum: 
    name: "{{ item }}"
    state: present
  with_items:
    - perl  
    - libxml2
    - libxml2-devel
    - libjpeg
    - libjpeg-devel
    - libpng
    - libpng-devel
    - freetype
    - freetype-devel

- name: Download "{{ PHP_Version }}" Package, and release
  unarchive: src="{{ Down_PHP_Package }}" dest="{{ Release_dir }}" remote_src=True

- name: Download "{{ PHP_Script }}"
  get_url: url="{{ Down_PHP_Script }}" dest="{{ Release_dir }}/{{ PHP_Version }}"
  
- name: Run "{{ PHP_Script }}" 
  script: /bin/bash "{{ Release_dir}}/{{ PHP_Version }}/{{ PHP_Script }}" "{{ PHP_Version }}"
 
- name: Build php.ini file
  template:
    src: php.ini-development
    dest: /usr/local/lib/php.ini
  become: yes
  
- name: Build php-fpm.conf File
  template:
    src: php-fpm.conf.default
    dest: /usr/local/etc/php-fpm.conf
    mode: 0644
  become: yes

- name: Build PHP_SERVICE File
  template:
    src: php-fpm
    dest: /etc/init.d/php-fpm
    mode: 0755
  become: yes
  
- name: Delete Old PHP_SERVICE File
  command: chkconfig --del php-fpm
  
- name: Add New PHP_SERVICE File
  command: chkconfig --add php-fpm
  
- name: Configuration PHP_SERVICE
  command: chkconfig php-fpm on

  notify: restart php-fpm
  