---
- name: Install libselinux-python
  yum: name=libselinux-python state=present

- name: Reload ansible_facts
  setup:

- name: Create Package_dir
  file: path="{{ Package_dir }}" state=directory mode=0755

- name: Create Release_dir
  file: path="{{ Release_dir }}" state=directory mode=0755

- name: Copy the EPEL repository definition
  copy: src=epel.repo dest=/etc/yum.repos.d/epel.repo

- name: Create the GPG key for EPEL
  copy: src=RPM-GPG-KEY-EPEL-6 dest=/etc/pki/rpm-gpg

- name: Set up iptables rules
  copy: src=iptables-save dest=/etc/sysconfig/iptables
  notify: restart iptables